# Generated by Django 5.2.1 on 2025-05-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente', models.CharField(max_length=100)),
                ('medico', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('horario', models.TimeField()),
            ],
        ),
    ]
